# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c66e4d80a628daf0e354d69272612b457767a3cb82b668e12d8e12c9fb680f036e0f461aa612508f10ddcb8075f8ff91347ebd136c02bc2ba00d13073cd1a91f

test:
  secret_key_base: 174ffbb7b8faf7eb0e519060f58add8e389fc12882ef01e2f5f413c9ceccb6816898fc406a4449a568e9f81bde627f45245a7ab903b3b623a8b5fa366596a2e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
